
# platform :ios, '9.0'

target 'Model' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'WeiboSDK', '~> 3.1.3'
pod 'ZFPlayer', '~> 2.1.3'
pod 'ReactiveCocoa', '~> 2.5'
  # Pods for Model

  target 'ModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
