# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KVO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'ReactiveCocoa', '~> 2.5'
  # Pods for KVO

  target 'KVOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KVOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
