# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pro22' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.2' #第三方约束
pod 'IQKeyboardManager', '~> 3.3.0' #键盘遮挡控件
 pod 'SDWebImage', '~> 4.0.0'
pod 'MJRefresh', '~> 3.1.12'
  # Pods for Pro22

  target 'Pro22Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pro22UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
