# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pro18' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.2' #第三方约束
pod 'IQKeyboardManager', '~> 3.3.0' #键盘遮挡控件
  # Pods for Pro18

  target 'Pro18Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pro18UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
