# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pro20' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'SDWebImage', '~> 4.0.0'
  # Pods for Pro20

  target 'Pro20Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pro20UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
