# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pro23' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
  # Pods for Pro23

  target 'Pro23Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pro23UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
