# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACCommand.2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'ReactiveCocoa', '~> 2.5'
  # Pods for RACCommand.2

  target 'RACCommand.2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACCommand.2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
