# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioDemon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod ‘AFNetworking’, ‘~>3.1.0’
  pod 'DOUAudioStreamer', '~> 0.2.15'
  pod 'Masonry'
  pod 'FreeStreamer', '~> 3.7.2'

  # Pods for AudioDemon

  target 'AudioDemonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioDemonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
